stages:
  - deploy-stage

variables:
  KUBE_NAMESPACE: "vpc" 
  HELM_RELEASE_NAME: "redis-cluster" 
  CHART_PATH: "."     

deploy-stage:
  stage: deploy-stage
  image:
    name: alpine/helm:3.14.1 
    entrypoint: [""]
  script:
    - echo "Deploying/Upgrading Redis Cluster using Helm..."
    - helm upgrade --install "$HELM_RELEASE_NAME" "$CHART_PATH" --kubeconfig "$CI_KUBE_CONFIG_STG" -n "$KUBE_NAMESPACE"
  when: manual
  only:
    - develop