stages:
  - deploy

variables:
  KUBE_NAMESPACE: "hmd" 
  HELM_RELEASE_NAME: "redis-cluster" 
  CHART_PATH: "."     

deploy:
  stage: deploy
  image:
    name: alpine/helm:3.14.1 
    entrypoint: [""]
  script:
    - echo "Deploying/Upgrading Redis Cluster using Helm..."
    - helm upgrade --install "$HELM_RELEASE_NAME" "$CHART_PATH" --kubeconfig "$KUBE_CONFIG" -n "$KUBE_NAMESPACE"
    - echo "$(kubectl exec -it redis-0 -n redis -- redis-cli -c cluster info)"
    - echo "$(kubectl exec -it redis-0 -n redis -- redis-cli -c cluster nodes)"
