replicaCount: 6
image:
  repository: redis
  tag: 7.2-alpine
  pullPolicy: IfNotPresent
resources: {}
storage:
  size: 8Gi
  class: standard
redis:
  auth:
    enabled: true
    password: "REDIS_PASS"
