apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  labels:
    app: redis
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600  # Automatically delete job after 10 minutes if successful
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-cluster-init
          image: redis:7.2-alpine
          command:
            - sh
            - -c
            - |
              echo "Waiting for Redis pods..."
              while [ $(kubectl get pods -n rf -l app=redis -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | wc -w) -lt 6 ]; do
                echo "Waiting for all Redis pods to be Running...";
                sleep 3;
              done
              echo "Checking cluster state..."
              redis-cli -h redis-0.redis-headless -p 6379 cluster info | grep 'cluster_state:ok' && echo "Cluster already initialized" && exit 0

              echo "Creating Redis cluster..."
              redis-cli --cluster create \
                $(getent hosts redis-0.redis-headless | awk '{print $1}'):6379 \
                $(getent hosts redis-1.redis-headless | awk '{print $1}'):6379 \
                $(getent hosts redis-2.redis-headless | awk '{print $1}'):6379 \
                $(getent hosts redis-3.redis-headless | awk '{print $1}'):6379 \
                $(getent hosts redis-4.redis-headless | awk '{print $1}'):6379 \
                $(getent hosts redis-5.redis-headless | awk '{print $1}'):6379 \
                --cluster-replicas 1
